### PR TITLE
Fix compatibility with PHP 8

### PR DESCRIPTION
**Pull request by qzminski**

### CODE REVIEW

**Review by JanoschOltmanns — APPROVED** [review]

**Comment by qzminski** [comment]
Please hold on with the merge, I have a few more fixes 😉

**Comment by qzminski** [comment]
Okay, that would be it for now I think :+1:

**Comment by kraustomas** [comment]
> Okay, that would be it for now I think 👍

one more: Undefined array key "dma_simplegrid_additionalcolumnclasses" in vendor/dma/dma_simple_grid/src/dma_simple_grid/classes/DmaSimpleGrid.php on line 184

**Comment by qzminski** [comment]
@kraustomas fixed in [a46e59a](https://github.com/DMAGmbH/dma_simple_grid/pull/30/commits/a46e59abe9c6ace715b659c70f1436e982f42734).

**Comment by think-digital-agency** [comment]
Hi everyone, can you tell when this will be available via Contao Manager? Or could anyone tell me, how to use this fix right now? Would love to use the package with PHP 8.

**Comment by qzminski** [comment]
@JanoschOltmanns can we get this merged in? 😉

**Comment by JanoschOltmanns** [comment]
@qzminski unfortunately I don’t work at dma anymore.  I'm trying to clarify the maintenance so we can continue working on this extension

**Comment by qzminski** [comment]
Oh, sure, thanks!

**Comment by JanoschOltmanns** [comment]
@qzminski I maintain this extension now officially. A few overdue adjustments will follow shortly

**Pull request merged**
